// Fallback data when Supabase isn't configured yet — mirrors migration seed.
// Lets the UI run end-to-end before Jonah pastes the Supabase creds.

export const MOCK_BANKS = [
  { bank_id: 'm-customers', bank_name: 'Customers Bank', tier: 'T1', sdm_entity: 'SDM_INC',
    supported_currencies: ['USD'], accepts_lp_currencies: ['USD'],
    settlement_networks: ['FEDWIRE','CUBIX'],
    max_client_risk: 'MEDIUM', accepts_individuals: true,
    blocked_verticals: ['GAMING','GAMBLING','ATM_OPERATOR'],
    pricing_tier: 'BEST', settlement_speed: 'INSTANT', is_active: true,
    notes: 'USD domestic ONLY. Best pricing for USD. Cubix = instant/free settlements.' },
  { bank_id: 'm-bcb', bank_name: 'BCB Group', tier: 'T1', sdm_entity: 'SDM_INC',
    supported_currencies: ['USD','GBP','EUR'], accepts_lp_currencies: ['USD','GBP','EUR'],
    settlement_networks: ['SWIFT','BLINK'],
    max_client_risk: 'MEDIUM', accepts_individuals: false,
    blocked_verticals: ['GAMING','GAMBLING','ATM_OPERATOR'],
    pricing_tier: 'COMPETITIVE', settlement_speed: 'INSTANT', is_active: true,
    notes: 'Multi-currency. Blink = near-instant/free via Nonco/Flowdesk.' },
  { bank_id: 'm-openpay', bank_name: 'OpenPay', tier: 'T2', sdm_entity: 'SDM_INC',
    supported_currencies: ['USD','EUR','GBP','CHF','JPY','SGD','HKD','AUD'],
    accepts_lp_currencies: ['USD','EUR','GBP'],
    settlement_networks: ['SWIFT'], max_client_risk: 'HIGH', accepts_individuals: true,
    blocked_verticals: [], pricing_tier: 'PREMIUM', settlement_speed: 'T1', is_active: true,
    notes: 'Higher fees. Lenient on risk. Primary high-risk client bank. Takes USD/EUR/GBP from LPs, does FX to other currencies.' },
  { bank_id: 'm-equals', bank_name: 'Equals Money', tier: 'T2', sdm_entity: 'SDM_INC',
    supported_currencies: ['USD','EUR','GBP','CNY','CHF','JPY','SGD','HKD','AUD','AED'],
    accepts_lp_currencies: ['USD','EUR','GBP','CNY'],
    settlement_networks: ['SWIFT'], max_client_risk: 'HIGH', accepts_individuals: true,
    blocked_verticals: [], pricing_tier: 'PREMIUM', settlement_speed: 'T1', is_active: true,
    notes: 'Primary FX bank. Accepts USD/EUR/GBP/CNY from LPs, converts to any supported currency including AED.' },
  { bank_id: 'm-ripple', bank_name: 'Ripple (ODL)', tier: 'T2_SPECIALIST', sdm_entity: 'SDM_INC',
    supported_currencies: ['EUR','GBP','USD','AED'],
    accepts_lp_currencies: ['USDT','USDC'],
    settlement_networks: ['RIPPLE_ODL'],
    max_client_risk: 'MEDIUM', accepts_individuals: true, blocked_verticals: [],
    pricing_tier: 'BEST', settlement_speed: 'INSTANT', is_active: true,
    notes: 'SPECIALIST: stables-in, fiat-out ONLY. LP provides USDT/USDC; Ripple does conversion + delivery in target currency.' },
  { bank_id: 'm-neo', bank_name: 'Neo Financial', tier: 'T2', sdm_entity: 'SDM_INC',
    supported_currencies: ['CAD'], accepts_lp_currencies: ['CAD'],
    settlement_networks: ['EFT'],
    max_client_risk: 'MEDIUM', accepts_individuals: true, blocked_verticals: [],
    pricing_tier: 'STANDARD', settlement_speed: 'T1', is_active: true,
    notes: 'Deprecated for most clients. Only ~2 clients remain.' },
  { bank_id: 'm-connectfirst', bank_name: 'ConnectFirst CU', tier: 'T1_CAD', sdm_entity: 'SDM_INC',
    supported_currencies: ['CAD'], accepts_lp_currencies: ['CAD'],
    settlement_networks: ['EFT'],
    max_client_risk: 'MEDIUM', accepts_individuals: true,
    blocked_verticals: ['GAMING','GAMBLING','ATM_OPERATOR'],
    pricing_tier: 'BEST', settlement_speed: 'SAME_DAY', is_active: true,
    notes: 'Best option for CAD-jurisdiction clients.' },
  { bank_id: 'm-hrb', bank_name: 'Hamilton Reserve Bank (HRB)', tier: 'T3_DEDICATED', sdm_entity: 'SDM_INC',
    supported_currencies: ['USD'], accepts_lp_currencies: ['USD'],
    settlement_networks: ['SWIFT'],
    max_client_risk: 'MEDIUM', accepts_individuals: true, blocked_verticals: [],
    pricing_tier: 'STANDARD', settlement_speed: 'T1', is_active: true,
    notes: 'Single-client bank. Not for new client routing.' },
  { bank_id: 'm-oldglory', bank_name: 'Old Glory Bank', tier: 'T3', sdm_entity: 'SDM_USA',
    supported_currencies: ['USD'], accepts_lp_currencies: ['USD'],
    settlement_networks: ['FEDWIRE'],
    max_client_risk: 'LOW', accepts_individuals: true,
    blocked_verticals: ['GAMING','GAMBLING','ATM_OPERATOR'],
    pricing_tier: 'STANDARD', settlement_speed: 'SAME_DAY', is_active: true,
    notes: 'SDM USA entity bank. Oklahoma-based. Manual wire approval required.' }
];

export const MOCK_LPS = [
  { lp_id: 'm-nonco', lp_name: 'Nonco', supported_currencies: ['USD','EUR','GBP'],
    settlement_networks: ['BLINK','SWIFT'], preferred_banks: [], risk_tolerance: 'MEDIUM', is_active: true },
  { lp_id: 'm-flowdesk', lp_name: 'Flowdesk', supported_currencies: ['USD','EUR','GBP'],
    settlement_networks: ['BLINK','SWIFT'], preferred_banks: [], risk_tolerance: 'MEDIUM', is_active: true },
  { lp_id: 'm-dv', lp_name: 'DV Trading', supported_currencies: ['CAD'],
    settlement_networks: ['EFT'], preferred_banks: [], risk_tolerance: 'MEDIUM', is_active: true },
  { lp_id: 'm-cumberland', lp_name: 'Cumberland', supported_currencies: ['USD'],
    settlement_networks: ['CUBIX','FEDWIRE'], preferred_banks: [], risk_tolerance: 'MEDIUM', is_active: true },
  { lp_id: 'm-b2c2', lp_name: 'B2C2', supported_currencies: ['USD','EUR','GBP'],
    settlement_networks: ['CUBIX','SWIFT'], preferred_banks: [], risk_tolerance: 'MEDIUM', is_active: true },
  { lp_id: 'm-fireblocks', lp_name: 'Fireblocks (custody)', supported_currencies: ['USDT','USDC','BTC','ETH'],
    settlement_networks: ['CRYPTO','RIPPLE_ODL'], preferred_banks: [], risk_tolerance: 'MEDIUM', is_active: true },
  { lp_id: 'm-grandpay', lp_name: 'Grand Pay', supported_currencies: ['CNY','USD'],
    settlement_networks: ['SWIFT'], preferred_banks: ['m-equals'], risk_tolerance: 'MEDIUM', is_active: true,
    notes: 'CNY originator/counterparty per Curtis transcript. CNY → Equals → USD conversion flow.' }
];

export const MOCK_CLIENTS = [
  { client_id: 'c1', client_name: 'Paktra Gaming Ltd', entity_type: 'CORPORATION',
    business_vertical: 'GAMING', jurisdiction_country: 'MT', sdm_entity: 'SDM_INC',
    risk_rating: 'HIGH', kyc_status: 'APPROVED',
    currencies_traded: ['USD','EUR'], settlement_currencies: ['USD','EUR'],
    settlement_methods: ['SWIFT'], settlement_speed_sla: 'T0_SAME_DAY',
    beneficiary_country: 'MT', uses_stablecoins: false, priority_tier: 'P1', is_active: true },
  { client_id: 'c2', client_name: 'Toofan Real Estate', entity_type: 'CORPORATION',
    business_vertical: 'REAL_ESTATE', jurisdiction_country: 'AE', sdm_entity: 'SDM_INC',
    risk_rating: 'MEDIUM', kyc_status: 'APPROVED',
    currencies_traded: ['USDT','AED'], settlement_currencies: ['AED'],
    settlement_methods: [], settlement_speed_sla: 'T0_SAME_DAY',
    beneficiary_country: 'AE', uses_stablecoins: true, priority_tier: 'P1', is_active: true },
  { client_id: 'c3', client_name: 'Northern Lights Fintech', entity_type: 'CORPORATION',
    business_vertical: 'FINTECH', jurisdiction_country: 'CA', sdm_entity: 'SDM_INC',
    risk_rating: 'LOW', kyc_status: 'APPROVED',
    currencies_traded: ['CAD'], settlement_currencies: ['CAD'],
    settlement_methods: ['EFT'], settlement_speed_sla: 'T1_NEXT_DAY',
    beneficiary_country: 'CA', uses_stablecoins: false, priority_tier: 'P2', is_active: true }
];

export const MOCK_WEIGHTS = {
  id: 1, tier_weight: 30, settlement_speed_weight: 25, pricing_weight: 20,
  network_bonus_weight: 15, priority_bonus_weight: 10
};

// ---------------------------------------------------------------------
// Affinity rules — sourced from Curtis + Jonah transcript 2026-04-15.
// In mock mode we reference banks by bank_id (m-* IDs defined above).
// In Supabase mode these come from the affinity_rules table.
// ---------------------------------------------------------------------
export const MOCK_AFFINITY_RULES = [
  // CAD
  { rule_id: 'a-cad-ca',       label: 'CAD → ConnectFirst',
    currency: 'CAD', beneficiary_country: 'CA', requires_stables_in: null,
    required_sdm_entity: null, required_risk: null,
    bank_id: 'm-connectfirst', boost: 100, sort_order: 10, is_active: true,
    rationale: 'Canadian-based client trading CAD → ConnectFirst is the default rail per Curtis.' },
  { rule_id: 'a-cad-any',      label: 'CAD any-beneficiary → ConnectFirst',
    currency: 'CAD', beneficiary_country: null, requires_stables_in: null,
    required_sdm_entity: null, required_risk: null,
    bank_id: 'm-connectfirst', boost: 80, sort_order: 11, is_active: true,
    rationale: 'ConnectFirst is the primary CAD bank. Neo is deprecated.' },

  // CNY — Grand Pay flow
  { rule_id: 'a-cny',          label: 'CNY → Equals (Grand Pay flow)',
    currency: 'CNY', beneficiary_country: null, requires_stables_in: null,
    required_sdm_entity: null, required_risk: null,
    bank_id: 'm-equals', boost: 100, sort_order: 20, is_active: true,
    rationale: 'CNY from Grand Pay settles directly to Equals, converts to USD, wires out.' },

  // AED
  { rule_id: 'a-aed-uae-s',    label: 'AED + UAE + stables-in → Ripple ODL',
    currency: 'AED', beneficiary_country: 'AE', requires_stables_in: true,
    required_sdm_entity: null, required_risk: null,
    bank_id: 'm-ripple', boost: 100, sort_order: 30, is_active: true,
    rationale: 'Toofan pattern — stables → Fireblocks → Ripple → AED to UAE beneficiary. Cheaper than Equals.' },
  { rule_id: 'a-aed-fallback', label: 'AED fallback → Equals',
    currency: 'AED', beneficiary_country: null, requires_stables_in: false,
    required_sdm_entity: null, required_risk: null,
    bank_id: 'm-equals', boost: 60, sort_order: 31, is_active: true,
    rationale: 'When Ripple not eligible (no stables, or non-UAE beneficiary), Equals handles AED.' },

  // EUR
  { rule_id: 'a-eur-sepa-s',   label: 'EUR + SEPA + stables-in → Ripple ODL',
    currency: 'EUR', beneficiary_country: 'DE', requires_stables_in: true,
    required_sdm_entity: null, required_risk: null,
    bank_id: 'm-ripple', boost: 100, sort_order: 40, is_active: true,
    rationale: 'Ripple has great pricing for Euro-SEPA. Add a rule per SEPA country as needed.' },
  { rule_id: 'a-eur-bcb',      label: 'EUR (non-HIGH risk) → BCB',
    currency: 'EUR', beneficiary_country: null, requires_stables_in: null,
    required_sdm_entity: 'SDM_INC', required_risk: 'MEDIUM',
    bank_id: 'm-bcb', boost: 70, sort_order: 41, is_active: true,
    rationale: 'BCB is the primary EUR/GBP bank for non-high-risk SDM Inc. clients.' },
  { rule_id: 'a-eur-high',     label: 'EUR (HIGH risk) → OpenPay',
    currency: 'EUR', beneficiary_country: null, requires_stables_in: null,
    required_sdm_entity: null, required_risk: 'HIGH',
    bank_id: 'm-openpay', boost: 80, sort_order: 42, is_active: true,
    rationale: 'HIGH-risk clients cannot use BCB for EUR (Maple Wave rejection pattern). OpenPay is lenient.' },

  // GBP
  { rule_id: 'a-gbp-uk-s',     label: 'GBP + UK + stables-in → Ripple ODL',
    currency: 'GBP', beneficiary_country: 'GB', requires_stables_in: true,
    required_sdm_entity: null, required_risk: null,
    bank_id: 'm-ripple', boost: 100, sort_order: 50, is_active: true,
    rationale: 'Ripple enabled for GBP to UK beneficiaries on stables-in flows.' },
  { rule_id: 'a-gbp-bcb',      label: 'GBP (non-HIGH risk) → BCB',
    currency: 'GBP', beneficiary_country: null, requires_stables_in: null,
    required_sdm_entity: 'SDM_INC', required_risk: 'MEDIUM',
    bank_id: 'm-bcb', boost: 70, sort_order: 51, is_active: true,
    rationale: 'BCB is primary GBP bank for non-high-risk SDM Inc. clients.' },
  { rule_id: 'a-gbp-high',     label: 'GBP (HIGH risk) → OpenPay',
    currency: 'GBP', beneficiary_country: null, requires_stables_in: null,
    required_sdm_entity: null, required_risk: 'HIGH',
    bank_id: 'm-openpay', boost: 80, sort_order: 52, is_active: true,
    rationale: 'HIGH-risk clients cannot use BCB. OpenPay is lenient on risk.' },

  // USD
  { rule_id: 'a-usd-custom-m', label: 'USD → Customers Bank (strategic push, MEDIUM risk)',
    currency: 'USD', beneficiary_country: null, requires_stables_in: null,
    required_sdm_entity: 'SDM_INC', required_risk: 'MEDIUM',
    bank_id: 'm-customers', boost: 100, sort_order: 60, is_active: true,
    rationale: 'Push USD volume to Customers Bank — Cubix network = instant/free, best USD pricing.' },
  { rule_id: 'a-usd-custom-l', label: 'USD → Customers Bank (LOW risk)',
    currency: 'USD', beneficiary_country: null, requires_stables_in: null,
    required_sdm_entity: 'SDM_INC', required_risk: 'LOW',
    bank_id: 'm-customers', boost: 100, sort_order: 61, is_active: true,
    rationale: 'Same strategic push for LOW-risk clients.' },
  { rule_id: 'a-usd-bcb',      label: 'USD fallback → BCB',
    currency: 'USD', beneficiary_country: null, requires_stables_in: null,
    required_sdm_entity: 'SDM_INC', required_risk: 'MEDIUM',
    bank_id: 'm-bcb', boost: 60, sort_order: 62, is_active: true,
    rationale: 'BCB = next-best USD pricing. Blink via Nonco/Flowdesk = near-instant. Braza flow.' },
  { rule_id: 'a-usd-high',     label: 'USD (HIGH risk) → OpenPay',
    currency: 'USD', beneficiary_country: null, requires_stables_in: null,
    required_sdm_entity: null, required_risk: 'HIGH',
    bank_id: 'm-openpay', boost: 100, sort_order: 63, is_active: true,
    rationale: 'Paktra/Raw pattern. HIGH-risk USD clients go to OpenPay (Customers/BCB would flag + shut down).' },
  { rule_id: 'a-usd-china-s',  label: 'USD + China + stables-in → Ripple ODL',
    currency: 'USD', beneficiary_country: 'CN', requires_stables_in: true,
    required_sdm_entity: null, required_risk: null,
    bank_id: 'm-ripple', boost: 100, sort_order: 64, is_active: true,
    rationale: 'Only Ripple corridor outside normal-jurisdiction rule: USD to China with stables in.' },
  { rule_id: 'a-usd-usa',      label: 'USD + SDM_USA → Old Glory',
    currency: 'USD', beneficiary_country: null, requires_stables_in: null,
    required_sdm_entity: 'SDM_USA', required_risk: null,
    bank_id: 'm-oldglory', boost: 100, sort_order: 65, is_active: true,
    rationale: 'SDM USA clients default to Old Glory until Customers Bank USA onboards.' }
];
